apiVersion: extensions/v1beta1

kind: Deployment

metadata:
    name: openebs1

spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: openebs1
      spec:
        containers:
        - name: openebs1-container
          image: docker.io/aadiiitiii/openebs1:ver1
          ports:
          - containerPort: 80
