apiVersion: v1

kind: Service

metadata:
    name: openebs1-svc
    labels:
      app: openebs1

spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 32001
    selector:
      app: openebs1
